# =============================================
# BUILD CONFIG
# =============================================


# Dest config
src:							src
dest:             _site

# today
date:             <%= new Date() %>

# public assets
assets:           <%= site.dest %>
# Data
data:             <%= site.src %>/data
# Styles
styles:           <%= site.src %>/style
# Content
content:          <%= site.src %>/content
# Extensions
plugins:
  - assemble-contrib-permalinks
  - assemble-contrib-anchors

# Templates
pages:            <%= site.src %>/pages
partials:         <%= site.src %>/partials
layouts:          <%= site.src %>/layouts
helpers:       <%= site.src %>/helpers

# site metadata
title:						assemblog | a blog lovingly handcrafted with assemble static site generator
description:			a blog lovingly handcrafted with assemble static site generator
analytics: UA-XXXXX-X

